apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-infra
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/tungdev1209/hello-infra
  ref:
    branch: main
  secretRef:
    name: hello-infra-token
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tungdev1209/hello-app
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: hello-infra
  path: ./k8s/flux/traefik
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuer
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: hello-infra
  path: ./k8s/flux
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-app-config
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: hello-app
  path: ./k8s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-app
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: hello-app-config
  sourceRef:
    kind: GitRepository
    name: hello-infra
  path: ./k8s/flux/services/hello-app
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: hello-app-config
        optional: true
