apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${SERVICE_NAME}
spec:
  replicas: ${REPLICAS:=1}
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${SERVICE_IMAGE} # {"$imagepolicy": "flux-system:${SERVICE_NAME}-policy"}
          ports:
            - containerPort: ${SERVICE_PORT:=8080}
          resources:
            requests:
              cpu: ${CPU_REQUEST:=100m}
              memory: ${MEMORY_REQUEST:=128Mi}
            limits:
              cpu: ${CPU_LIMIT:=500m}
              memory: ${MEMORY_LIMIT:=256Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
    - port: 80
      targetPort: ${SERVICE_PORT:=8080}
