apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-app-config
  namespace: flux-system
data:
  SERVICE_NAME: hello-app
  SERVICE_HOST: hello.teleprintor.com
  SERVICE_IMAGE: 136583899808.dkr.ecr.us-east-1.amazonaws.com/teleprinter-hello-app:v1.0.8 # {"$imagepolicy": "flux-system:hello-app-policy"}
  SERVICE_PORT: "8080"
  REPLICAS: "2"
  CPU_REQUEST: "100m"
  CPU_LIMIT: "500m"
  MEMORY_REQUEST: "128Mi"
  MEMORY_LIMIT: "256Mi"
