apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-app-image-config
  namespace: flux-system
data:
  SERVICE_IMAGE: 136583899808.dkr.ecr.us-east-1.amazonaws.com/teleprinter-hello-app:v1.0.9 # {"$imagepolicy": "flux-system:hello-app-policy"}
